### ISSUE TITLE
Is it possible use IIS rather azure to publish the asp.net sharing service?

### ISSUE THREAD

**Issue by peterchen2001** [BerwinZ/Multiplayer_AR_Robots_Battle#1]
Is it possible use my own http server with port rather than azure website to publish the asp.net sharing service?

**Comment by BowenBZ** [comment]
I haven't tried this before but I think the sharing service could be deployed to another server, just need to remove some Azure related things like the token related part. The sharing service seems like a simple web service that stores the posted anchor data and return the respective anchor when handling the get request.
